Difference between ML and DL
   - Data
   - Feature extraction and engineering
   - Neural Networks

parts of tensorflow
   - graphs 
   - sessions

Rank: dimension of a tensor object
Tensors shape and dimeninsions determines its rank, which is described using rank,shape and dimension number.
There are 3 types of variables:
1. Constants(values remain constant)
2. Variables(values keep changing)
3. Placeholder(at runtime values are fed)
4. Session( run to execute the command)

In [1]:
import tensorflow as tf

In [2]:
hello=tf.constant('hello world')
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [3]:
sess=tf.Session()
sess.run(hello)

b'hello world'

In [4]:
stats=tf.Variable(0)
one=tf.constant(1)
new_values=tf.add(stats,one)
update=tf.assign(stats,new_values) #assigns newvalue to state

In [5]:
init_op=tf.global_variables_initializer() #only for type variables

In [6]:
sess.run(init_op)

In [7]:
print(sess.run(new_values))

1


### Placeholders

In [8]:
sess=tf.Session()

In [9]:
a=tf.placeholder(tf.float32)
a

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [10]:
b=a*2
sess.run(b,feed_dict={a:30})

60.0

In [11]:
dictionary={a:[[[1,2,3],[4,5,6],[6,8,9],[10,11,12],[14,15,16],[18,19,20],[22,23,24],[26,27,28]]]}

In [12]:
b=a*2
result=sess.run(b,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [12. 16. 18.]
  [20. 22. 24.]
  [28. 30. 32.]
  [36. 38. 40.]
  [44. 46. 48.]
  [52. 54. 56.]]]


In [13]:
#after creating a session the session needs to be closed
sess.close()

#### another way to run a session, explicitly opening a session

In [14]:
with tf.Session() as sess:
    result=sess.run(b,feed_dict={a:3.5})
print(result)

7.0


In [15]:
with tf.Session() as sess:
    result=sess.run(b,feed_dict=dictionary)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [12. 16. 18.]
  [20. 22. 24.]
  [28. 30. 32.]
  [36. 38. 40.]
  [44. 46. 48.]
  [52. 54. 56.]]]


### Better Example

In [16]:
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)

In [18]:
sess=tf.Session()

In [20]:
c=a+b

In [22]:
result=sess.run(c,feed_dict={a:10,b:20})
print(result)

30.0


In [25]:
d=a*c

In [26]:
a_val=[1,2,3]
b_val=[3,4,5]

In [27]:
result=sess.run(d,feed_dict={a:a_val,b:b_val}) # it will accept other variables also
print(result)

[ 4. 12. 24.]


### Default Graphs

In [28]:
graph=tf.get_default_graph()

In [29]:
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'mul_1/y' type=Const>,
 <tf.Operation 'mul_1' type=Mul>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'Placeholder_2' type=Placeholder>,
 <tf.Operation 'add_1' type=Add>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'mul_2' type=Mul>,
 <tf.Operation 'mul_3' type=Mul>,
 <tf.Operation 'mul_4' type=Mul>]

In [30]:
a=tf.constant(10,name='a')

In [38]:
operations=graph.get_operations()
operations

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'mul_1/y' type=Const>,
 <tf.Operation 'mul_1' type=Mul>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'Placeholder_2' type=Placeholder>,
 <tf.Operation 'add_1' type=Add>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'mul_2' type=Mul>,
 <tf.Operation 'mul_3' type=Mul>,
 <tf.Operation 'mul_4' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>,
 <tf.Operation 'b' type=Const>]

In [32]:
a=tf.constant(10,name='a')
b=tf.constant(20,name='b')

In [41]:
c=tf.add(a,b,name='c')

In [42]:
operations=graph.get_operations()
operations

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'mul_1/y' type=Const>,
 <tf.Operation 'mul_1' type=Mul>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'Placeholder_2' type=Placeholder>,
 <tf.Operation 'add_1' type=Add>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'mul_2' type=Mul>,
 <tf.Operation 'mul_3' type=Mul>,
 <tf.Operation 'mul_4' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'd' type=Mul>,
 <tf.Operation 'c' type=Add>]

In [43]:
d=tf.multiply(a,b,name='d')
operations=graph.get_operations()
operations

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'mul_1/y' type=Const>,
 <tf.Operation 'mul_1' type=Mul>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'Placeholder_2' type=Placeholder>,
 <tf.Operation 'add_1' type=Add>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'mul_2' type=Mul>,
 <tf.Operation 'mul_3' type=Mul>,
 <tf.Operation 'mul_4' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'd' type=Mul>,
 <tf.Operation 'c' type=Add>,
 <tf.Operation 

In [44]:
e=tf.multiply(c,d,name='e')
operations=graph.get_operations()
operations

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'mul_1/y' type=Const>,
 <tf.Operation 'mul_1' type=Mul>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'Placeholder_2' type=Placeholder>,
 <tf.Operation 'add_1' type=Add>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'mul_2' type=Mul>,
 <tf.Operation 'mul_3' type=Mul>,
 <tf.Operation 'mul_4' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'd' type=Mul>,
 <tf.Operation 'c' type=Add>,
 <tf.Operation 

In [45]:
print(sess.run(e))

6000


### Demo code to implement a simple function x^2*y+y+c where x=3,y=4,c=2


In [3]:
sess=tf.Session()

In [4]:
x=tf.Variable(3)
y=tf.Variable(4)
c=tf.constant(2)

In [7]:
z=x*x*y+y+c

In [8]:
init=tf.global_variables_initializer()
sess.run(init)

In [18]:
result=sess.run(z,feed_dict={x:3,y:4})
print(result)

42


#### or

In [9]:
print(sess.run(z))

42


In [10]:
sess.close()

#### using the placeholder

In [34]:
sess=tf.Session()

In [38]:
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
c=tf.constant(5.0)

In [39]:
p=int(input('Enter an int value'))
q=int(input('Enter an int value'))
# r=int(input('Enter an constant value'))

Enter an int value7
Enter an int value4


In [40]:
z=x*x*y+y+c

In [41]:
print(sess.run(z,feed_dict={x:p,y:q}))

205.0


1. write a program to calculate the distance travelled by an object use the equaion of motion: s= ut + 1/2at^2.
2. The object started with initial velocity of 50m/s and is moving with a constant acc of 40m/s2. Time needs to be fed on runtime   

In [95]:
sess=tf.Session()

In [67]:
u=tf.constant(50.0)
t=tf.placeholder(tf.float32)
a=tf.constant(40.0)

In [71]:
time=float(input('Enter the time '))

Enter the time 10


In [69]:
s=u*t+0.5*a*t**2

In [72]:
print(sess.run(s,feed_dict={t:time}))

2500.0


### Regular Multiplication of vectors

Good Practice using tensorflow
- import libraries
- defining the variables
- import the data
- creating graphs and data cleaning
- create session and executin

In [6]:
x=tf.Variable([[1,2,3],[4,5,6]])
y=tf.Variable([[7,8,9],[10,11,12]])

In [14]:
init=tf.global_variables_initializer()

In [8]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(tf.multiply(x,y)))
    print(sess.run(tf.multiply(y,x)))
    print(sess.run(tf.multiply(x,10)))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 7 16 27]
 [40 55 72]]
[[ 7 16 27]
 [40 55 72]]
[[10 20 30]
 [40 50 60]]


#### a small exercise

In [25]:
x=tf.Variable([[10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,150,160]])
y=tf.Variable([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [26]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print('-------------simple multiplication-------')
    print(sess.run(tf.multiply(x,y)))
    print('-------------using matmul---------------')
    print(sess.run(tf.matmul(x,y)))

-------------simple multiplication-------
[[  10   40   90  160]
 [ 250  360  490  640]
 [ 810 1000 1210 1440]
 [1690 1960 2250 2560]]
-------------using matmul---------------
[[ 900 1000 1100 1200]
 [2020 2280 2540 2800]
 [3140 3560 3980 4400]
 [4260 4840 5420 6000]]


In [64]:
x=tf.Variable([[1,2,3],[4,5,6]])
y=tf.Variable([[7,8],[9,10],[11,12]])

In [68]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.matmul(x,y)))

[[ 58  64]
 [139 154]]


In [61]:
x=tf.Variable([[1,2],[4,5]])
y=tf.Variable([[7,8],[9,10],[11,12]])

In [69]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.matmul(x,y)))

[[ 58  64]
 [139 154]]


In [74]:
x=tf.Variable([[150,250,750],[500,600,800],[900,200,450]])
y=tf.Variable([[390,890,790]])
# y=tf.Variable([[390],[890],[790]]) without using transpose
y=tf.transpose(y)

In [75]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.matmul(x,y)))

[[ 873500]
 [1361000]
 [ 884500]]


### Demo for training a simple linear regression model in Tensorflow. To help understand the trainng process

- simple linear regression is also called best fit model
- the predicted values for a target variable is called inference

y = m * x + c

In [126]:
m=tf.Variable([.1],tf.float32)
c=tf.Variable([-.1],tf.float32)

In [127]:
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)

#### linear model

In [128]:
linear_model=m*x+c

#### loss

In [129]:
squared=tf.square(linear_model-y)
loss=tf.reduce_sum(squared)

#### select an optimizer

In [130]:
optimizer=tf.train.GradientDescentOptimizer(0.01)

#### minimize the loss using optimizer

In [131]:
train=optimizer.minimize(loss)

#### run the code

In [132]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(1000):
        sess.run(train,{x:[1,2,3,4],y:[0,-1,-2,-3]})
    print(sess.run([m,c]))

[array([-0.99999744], dtype=float32), array([0.9999925], dtype=float32)]


### Demo to use the optimizer to reduce the cost fucntion on a quadratic equation x^2-10x+25=0 (answer : 5)
              

the optimizer finds the value which solves the cost function(quadratic equation) which bring the value to zero

In [2]:
x=tf.Variable(0.0)

In [7]:
cost=x**2-20*x+100 #defines the error

In [4]:
optimizer=tf.train.GradientDescentOptimizer(0.01)

In [9]:
train=optimizer.minimize(cost)

In [10]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(1000):
        sess.run(train)
    print(sess.run(x))

9.999977


### Code to reshape and max value

In [12]:
x=tf.Variable([1,2,3,4,5,6])
y=tf.Variable([[1,2],[3,4],[5,6]])
z=tf.Variable([[1,9],[8,2],[3,7]])

In [22]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.reshape(y,[2,3])))

[[1 2 3]
 [4 5 6]]


argmax gives the index  of the max value between column(value = 0) and rows(value = 1)

In [31]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(y))
    print('column-wise max value at index ',sess.run(tf.argmax(y,0)))
    print('--------------------')
    print('row-wise max value at index ',sess.run(tf.argmax(y,1)))

[[1 2]
 [3 4]
 [5 6]]
column-wise max value at index  [2 2]
--------------------
row-wise max value at index  [1 1 1]


### Write the code to solve the following fucntion for x^4*y^3*z^2+5*y^4*x^3*z^3*x^2*y+100 for x=10,y=20,z=30 and x=20,y=50,z=5

In [42]:
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
z=tf.placeholder(tf.float32)

In [43]:
X=int(input('Enter a number '))
Y=int(input('Enter a number '))
Z=int(input('Enter a number '))

Enter a number 10
Enter a number 20
Enter a number 30


In [44]:
tfdict={x:X,y:Y,z:Z}

In [45]:
result=(x**4)*(y**3)*(z**2)+5*(y**4)*(x**3)*(z**3)*(x**2)*y+10000

In [46]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(result,feed_dict=tfdict))

4.3200074e+16
